version: '3.9'

services:
  redis:
    container_name: my-redis
    image: redis:alpine
    restart: always
    ports:
      - "6377:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    container_name: my-postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_destination=stderr"]


volumes:
  redis-data:
  postgres-data:

networks:
  my-network:
    driver: bridge